apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: starboard
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://aquasecurity.github.io/helm-charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard
  namespace: starboard
spec:
  chart:
    spec:
      chart: aqua/starboard
      sourceRef:
        kind: HelmRepository
        name: starboard-operator
        namespace: flux-system
      version: 0.10.3
  interval: 1m0s
